name: Test
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [namespace-profile-default, namespace-profile-default-arm64, namespace-profile-macos-sm]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - run: |
        git submodule update --init actions-toolkit
        cd actions-toolkit/packages/artifact
        npm install 

    - name: npm install
      run: npm install

    - name: Compile
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Format
      run: npm run format-check

    - name: Create artifacts
      run: |
        mkdir -p path/to/artifact-A
        mkdir -p path/to/artifact-B
        echo "Lorem ipsum dolor sit amet" > path/to/artifact-A/file-A.txt
        echo "Hello world from file B" > path/to/artifact-B/file-B.txt

    - name: Upload artifact A
      uses: namespace-actions/upload-artifact@v0
      with:
        name: Artifact-A-${{ matrix.runs-on }}
        path: path/to/artifact-A

    - name: Upload artifact B
      uses: namespace-actions/upload-artifact@v0
      with:
        name: Artifact-B-${{ matrix.runs-on }}
        path: path/to/artifact-B

    # Test downloading a single artifact
    - name: Download artifact A
      uses: ./
      with:
        name: Artifact-A-${{ matrix.runs-on }}
        path: some/new/path

    # Test downloading an artifact using tilde expansion
    - name: Download artifact A
      uses: ./
      with:
        name: Artifact-A-${{ matrix.runs-on }}
        path: ~/some/path/with/a/tilde

    - name: Verify successful download
      run: |
        str="Lorem ipsum dolor sit amet"
        if [[ $(< some/new/path/file-A.txt) != "$str" ]]; then
            exit 1
        fi
        
        if [[ $(< ~/some/path/with/a/tilde/file-A.txt) != "$str" ]]; then
            exit 1
        fi

    # Test downloading both artifacts at once
    - name: Download all Artifacts
      uses: ./
      with:
        path: some/other/path

    - name: Verify successful download
      run: |
        $fileA = "some/other/path/Artifact-A-${{ matrix.runs-on }}/file-A.txt"
        $fileB = "some/other/path/Artifact-B-${{ matrix.runs-on }}/file-B.txt"

        str="Lorem ipsum dolor sit amet"
        if [[ $(< $fileA) != "$str" ]]; then
            exit 1
        fi
        
        str="Hello world from file B"
        if [[ $(< $fileB) != "$str" ]]; then
            exit 1
        fi

    # Test glob downloading both artifacts to same directory
    - name: Download all Artifacts
      uses: ./
      with:
        pattern: Artifact-*
        path: single/directory
        merge-multiple: true

    - name: Verify successful download
      run: |
        $fileA = "single/directory/file-A.txt"
        $fileB = "single/directory/file-B.txt"

        str="Lorem ipsum dolor sit amet"
        if [[ $(< $fileA) != "$str" ]]; then
            exit 1
        fi
        
        str="Hello world from file B"
        if [[ $(< $fileB) != "$str" ]]; then
            exit 1
        fi
